### ISSUE TITLE
Add Read me on Atmosphere

### ISSUE THREAD

**Issue by jadsonlourenco** [Goluis/cottz-iron-query#1]
Very interesting that package. You can update the information in the Atmosphere? 
It would be nice if you can add more examples of using on description, perhaps to show the difference between this package and use regular session, etc. 

Thank you!

**Comment by lfades** [comment]
Hi Jadson, I had not realized that the readme did not appear in atmosphere, thanks for telling me

**Comment by lfades** [comment]
Jadson, you know why my readme is not in atmosphere?, I already try uploading a new version of the package and using the following command

``` js
meteor admin change-homepage cottz:iron-query 'https://github.com/Goluis/cottz-iron-query.git'
```

**Comment by jadsonlourenco** [comment]
No, unfortunately I don't have packages on Atmosphere, only collaborate with an another but there was already published, and see the same "read me" of repository. Sorry.

I'm still learning Meteor advanced mode, but soon I will launch some packages to help others.

**Comment by jadsonlourenco** [comment]
@Goluis new release of Meteor has new options to packages: https://www.meteor.com/blog/2015/01/20/meteor-show

**Comment by lfades** [comment]
My readme magically appeared with the new version of meteor
